### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nanoeray** [IronCPlusPlus/PufferPanel-FiveM#1]
its not works anymore could you update for new versions?

**Comment by IronCPlusPlus** [comment]
Sure, sorry for the long delay.

I'll look into this Friday.

**Comment by IronCPlusPlus** [comment]
Updated the FiveM, it is using the UUID of the current of 8/29/2020. Though, I won't be maintaining this for too long; 

Overall, its change of version; I added the steam web API key, which could've been added to your cfg.

Anyways, take care!
